BradenM/micropy-cli

- Makefile
- micropy/stubs/schema.json
- micropy/stubs/stubs.py
- micropy/utils/__init__.py
- micropy/utils/validate.py
- tests/test_validator.py
- tests/test_validator/fail.json
- tests/test_validator/pass.json
- tests/test_validator/schema.json
* Created utils module
* Added Validator Utility (small wrapper around jsonschema.validate)
> feat(utils): Utils Module and Validator Utility 

- micropy/stubs/source.py
- tests/data/test_source.json
- tests/test_stub_source.py
Implemented abstractions for access to stub repos.
> feat(stubs): Stub Repositories 

- micropy/cli.py
- micropy/logger.py
- micropy/stubs/source.py
- micropy/stubs/stubs.py
- micropy/utils/helpers.py
- tests/conftest.py
- tests/data/test_source.xml
- tests/test_cli.py
- tests/test_stub_source.py
- tests/test_stubs.py
- tests/test_utils.py
Adds ability to search stub repos via a stub package name query
> feat(cli): Search Available Stubs

- .gitmodules
- Pipfile
- micropy/cli.py
- micropy/logger.py
- micropy/main.py
- micropy/utils/pybwrapper.py
- setup.py
- tests/test_cli.py
- tests/test_main.py
- tests/test_pyboardwrapper.py
Update `micropy stubs create <port>` with:
* Better success rate
* Better output
* Increased coverage
* Handle more errors
> Device Stub Creation Updates and Fixes

- .gitignore
- Makefile
- Pipfile
- micropy/project/template.py
- tests/test_template.py
> v2.1.1 Hotfix

- .gitignore
- micropy/project/checks.py
- micropy/project/project.py
- micropy/project/template.py
- tests/conftest.py
- tests/test_checks.py
- tests/test_cli.py
- tests/test_project.py
- tests/test_template.py
Implemented template checks.
Created VSCode Template check for ms-python extension. Warns user if version is below minimum requirement.
> feat: Template Checks, MS-Python Check

- Pipfile
- micropy/cli.py
- micropy/data/__init__.py
- micropy/exceptions.py
- micropy/logger.py
- micropy/main.py
- micropy/project/project.py
- micropy/utils/__init__.py
- micropy/utils/decorators.py
- tests/conftest.py
- tests/test_cli.py
- tests/test_main.py
- tests/test_project.py
- tests/test_stubs.py
- tests/test_template.py
Overhaul of the current method of State Management.
Fixes some major design issues that have been a pain, rewrites some of the nasty bits, improve performance. 
Will simplify future code additions/changes.
> feat: Restructure MicroPy State Management

- .github/workflows/main.yml
- micropy/utils/helpers.py
- tests/test_pyboardwrapper.py
- tests/test_stubs/esp32_test_stub
- tests/test_stubs/esp32_test_stub/frozen/ntptime.py
- tests/test_stubs/esp32_test_stub/frozen/ntptime.pyi
- tests/test_stubs/esp32_test_stub/info.json
- tests/test_stubs/esp32_test_stub/stubs/machine.py
- tests/test_stubs/esp32_test_stub/stubs/modules.json
- tests/test_stubs/esp8266_test_stub
- tests/test_stubs/esp8266_test_stub/frozen/ntptime.py
- tests/test_stubs/esp8266_test_stub/frozen/ntptime.pyi
- tests/test_stubs/esp8266_test_stub/info.json
- tests/test_stubs/esp8266_test_stub/stubs/machine.py
- tests/test_stubs/esp8266_test_stub/stubs/modules.json
- tests/test_template.py
> tests(windows): Fix tests that fail on Windows

- .github/workflows/main.yml
- micropy/project/modules/packages.py
- tox.ini
Handle package not found or other unknown errors when adding a package
Closes #68
> fix: Handle Errors when adding Packages

- micropy/project/modules/modules.py
If a hooked function had **kwargs passed to it, HookProxy would fail.
This fixes that issue by recursively removing extra kwargs until either a match is found or it runs out of kwargs.
> fix: HookProxy failed to resolve with kwargs

- micropy/project/modules/packages.py
- micropy/project/project.py
Replace old project cache interface with a new Config instance
> feat(project): Replace Project Cache with Config Instance

- micropy/project/template.py
- micropy/project/template/.vscode/extensions.json
if using vscode integration, generate .vscode/extensions.json with the appropriate extensions for
micropy-cli. this way they are recommended to the user by vscode
closes #84
> feat(project): generate recommended extensions with vscode integration

- micropy/project/template.py
Fixes #108 
Pretty straight-forward change, now that I can build ;-)
Check if the file does not exist, then create it (the mainline case and uses the previous code)
If the file does exist, then update it instead.
> Update existing settings

- .gitignore
- .vscode/launch.json
- micropy/project/template.py
- micropy/project/template/.pylintrc
- tests/test_template.py
I finally managed to figure out how to download / configure / run and debug this in my own machine 
( ill try to add some hard learned how-to documentation ) 
after that it turned out to be a simple change that I hope you can merge to close #96 even if that is just an in-between step to the other changes you started in #97 
changes are only to the jijnja template file 
- no code added, just a keyword change to align to template
- no tests added, but a few tweaks to recognize the new template
> template update for pylint rc

- .github/workflows/main.yml
- .pre-commit-config.yaml
- .tool-versions
- docs/requirements.txt
- micropy/main.py
- micropy/utils/stub.py
- poetry.lock
- pyproject.toml
- tests/test_utils.py
> Update project dependencies and CI test workflow

- .github/renovate.json5
- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yml
- ci(main): update poetry, resolve caching misses on win/macos, improve caching overall.
- ci(renovate): enable dependency dashboard.
> CI Main workflow caching fixes/improvements

- .editorconfig
- .github/codeql/codeql-config.yml
- .github/workflows/codeql-analysis.yml
- style(editorconfig): explicitly add py black profile, specify yaml
- ci(codeql): add codeql config with path exclusions
- ci(codeql): properly setup env in codeql workflow and cleanup.
> CodeQL Workflow updates and setup fixes.

- micropy/main.py
- micropy/stubs/manifest.py
- micropy/utils/types.py
> fix(utils):  Python <=3.8 typing compatibility issues.

- micropy/cli.py
- micropy/stubs/repo.py
- micropy/stubs/source.py
- micropy/stubs/stubs.py
- tests/test_stub_source.py
- tests/test_stubs.py
- feat(stubs): make `StubRepository.resolve_package` return `StubRepositoryPackage`
- feat(stubs): support reuse of `StubSource` instances, improvements.
- feat(stubs): `RepoStubLocator` locate strategy.
- feat(stubs): utilize locators in `StubManager`, resolve requirements from metadata.
- feat(cli): utilize stub source locators during add.
- test(stubs): update existing stubs unit test.
> Resolve stub dependencies from metadata, stub locators improvements.

- .github/actions/setup-micropy/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yml
- .tool-versions
- tests/test_cli.py
- chore(tools): update poetry in tool versions.
- ci(github): update poetry version + format.
> Fix CI cache related issues, update poetry to v1.3.1

- .github/actions/setup-micropy/action.yml
> Fix venv exact cache key in ci

- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yml
- .tool-versions
- chore(tools): update poetry to latest
- ci: update poetry to v1.3.2
> Update poetry to v1.3.2

- .github/workflows/changelog.yml
- .tool-versions
- chore(tools): update gh-chlog version
- ci: add changelog flow.
> Add changelog workflow.

- .github/workflows/release.yml
- CHANGELOG.md
> ci: add release workflow

- .github/workflows/release.yml
- .readthedocs.yml
- docs/conf.py
- ci(release): setup release-please backed release flow
- docs(conf): dynamically determine docs release version
> Integrate release-please into release flow

- .github/renovate.json5
- .pre-commit-config.yaml
- docs/requirements.txt
- micropy/stubs/package.py
- poetry.lock
- pyproject.toml
- release-please-config.json
- ci(pre-commit): add pre-commit ci config.
- ci(renovate): group non-major dev deps, allow automerge dev deps majors
> Renovate groups, pre-commit ci

- .github/actions/setup-micropy/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yml
- .github/workflows/publish.yml
- .tool-versions
- chore(tools): update poetry version
- ci: update poetry versions up 1.4.0
> chore: update poetry to v1.4.0

- micropy/pyd/backend_rshell.py
> fix(pyd): backend rshell excess consumer kwarg

- micropy/app/stubs.py
- feat(app): add exclude_defaults, improve help in stubs create command.
- docs(app): improve stubs create help.
> Add `exclude_defaults`, improve help for stubs create command.

- poetry.lock
- pyproject.toml
> chore(deps): Update mypy and micropython-stubber

- micropy/app/main.py
- tests/app/test_main.py
> fix(cli): re-add version as command
