BradenM/micropy-cli

- micropy/exceptions.py
- micropy/logger.py
- micropy/main.py
- micropy/project/template.py
- micropy/stubs/__init__.py
- micropy/stubs/stubs.py
- tests/data/esp8266_invalid_stub/modules.json
- tests/test_main.py
- tests/test_project.py
- tests/test_stubs.py
- tests/test_stubs/bad_test_stub/modules.json
- tests/test_stubs/esp32_test_stub/modules.json
- tests/test_stubs/esp8266_test_stub/modules.json
- tests/test_template.py
Move stub-related functionality away from `MicroPy` class to its own dedicated `StubManager` class that will handle all instances of `Stub`
Will open up for "remote" stubs later on, which can be downloaded and will be sourced from `micropy-stubs`
Closes #6
> feat(stubs): Stub Manager

- micropy/utils/__init__.py
- micropy/utils/pybwrapper.py
- tests/test_pyboardwrapper.py
Wraps rshell/pyboard in a class and provides the basic "run file", "copy dir" functionality that Micropy-cli needs to create stubs on a device.
Part of #11
> feat(pyb): PyboardWrapper Utility

- .gitmodules
- micropy/cli.py
- micropy/exceptions.py
- micropy/logger.py
- micropy/main.py
- micropy/project/template.py
- micropy/stubs/__init__.py
- micropy/stubs/stubs.py
- micropy/utils/pybwrapper.py
- tests/data/esp8266_invalid_stub/modules.json
- tests/test_main.py
- tests/test_project.py
- tests/test_pyboardwrapper.py
- tests/test_stubs.py
- tests/test_stubs/bad_test_stub/modules.json
- tests/test_stubs/esp32_test_stub/modules.json
- tests/test_stubs/esp8266_test_stub/modules.json
- tests/test_template.py
Closes #6 
Closes #11 
* test(stubs): Initial Stub Manager Tests
* test: More StubManager Tests, Invalid Stub Test Data
* fix: Fix some issues with tests and exceptions
* feat(log): Remove need to reinstantiate Log before adding
No longer need to reinstantiate Log before adding a new one
* feat(stubs): Stub Manager Basic Implementation
* feat: StubManager Add, Unique Stubs
Added stub add handlers to StubManager, forced all stubs in StubManager to be unique
* feat: Began Replacing Micropy.STUBS with StubManager
* test: Updated Tests with Micropy.STUBS as StubManager
* test(stubs): Various Tests new StubManager add method
* fix: Loaded stubs are suppose to be an instance attribute
* feat(stubs): Use Unique Stub name as instance hash, not repr
* feat(stubs): Added resource kwarg to …
> Stub Management, Logic Separation

- micropy/project/template.py
- micropy/project/template/.pylintrc
Insert Device Specific frozen modules into template files for better Intellisense and auto completion as described in [Josverl/micropython-stubber](https://github.com/Josverl/micropython-stubber)
> feat(stubs): Add Device Frozen Modules to Templates

- micropy/project/project.py
- micropy/project/template.py
- micropy/project/template/.pylintrc
- micropy/stubs/source.py
- micropy/stubs/stubs.py
- micropy/utils/helpers.py
- tests/test_project.py
- tests/test_stubs.py
- tests/test_template.py
Instead of using the absolute paths to `$HOME/.micropy` folder in `settings.json` and `.pylintrc`, this creates a `<PROJECT_NAME>/.micropy` folder where used stubs are symlinked. This way, they can be referenced from `settings.json` as so:
```json
"setting_name" : [
"${workspaceRoot}/.micropy/micropython/frozen",
"${workspaceRoot}/.micropy/esp32-micropython-1.11.0/frozen",
"${workspaceRoot}/.micropy/esp32-micropython-1.11.0/stubs"
]
```
> NOTE: This requires the VSCode Python extension (which you probably have anyways if your using this.) See microsoft/vscode#2809 for more details.
and from .pylint rc:
```python
init-hook='import sys;sys.path.insert(1, ".micropy/micropython/frozen");sys.path.insert(1, ".micropy/esp32-micropython-1.11.0/frozen");sys.path.insert(1, …
```
> feat(project): Micropy Project Folder

- micropy/cli.py
- micropy/project/project.py
- micropy/stubs/stubs.py
- tests/data/project_test/micropy.json
- tests/test_cli.py
- tests/test_project.py
Adds a `micropy.json` file to each project, used to resolve stubs in `.micropy/`
Unlike `.micropy/`, this file will be included in source control. Its similar in purpose to a `package.json`, but for stub packages instead. 
Although subject to (and likely will) change, here is currently simple schema:
```json
{
"name": "NewProject",
"stubs": {
"esp32-micropython-1.11.0": "1.2.0",
"custom-stub": "./local/path/on/VCS"
}
}
```
Using this file, running `micropy` in a projects working directory will retrieve any needed stubs and generate the project local `.micropy/` directory. 
This effectively allows micropy to be near completely VCS compliant, and once its complete users will be able to match a given micropy workspace on Github (or wherever) after cloning by running `micropy` (similar to …
> feat(project): Micropy Project Info File

- micropy/logger.py
When running micropy in a windows environment, cleaning a message before writing it to the log raised a UnicodeDecodeError.
Closes #31
> fix: Unicode Error raised when logging on Windows

- micropy/project/project.py
- tests/test_project.py
After creating a project, a ValueError is raised when attempting to get the relative path of the new
Project. This is fixed by setting the project path as an absolute path instead of resolving it.
> fix: ValueError raised after Creating Project in Windows

- micropy/cli.py
- micropy/project/project.py
- micropy/project/template.py
- micropy/project/template/pymakr.conf
- tests/test_cli.py
- tests/test_project.py
- tests/test_template.py
Makes templates optional and allows users to select which to use.
Usage:
* Via Prompt:
```shell
micropy init
MicroPy  Creating New Project
? Project Name NewProject
? Choose any Templates to Generate                                                          
» ○ VSCode Settings for Autocompletion/Intellisense 
○ Pymakr Configuration
○ Pylint Micropython Settings
○ main.py & boot.py files
```
* Via Flags
`micropy init -t vscode -t pymakr -t pylint`
> feat(project): Make Templates Optional via CLI

- .gitignore
- Pipfile
- micropy/cli.py
- micropy/project/project.py
- micropy/project/template.py
- micropy/utils/helpers.py
- setup.cfg
- setup.py
- tests/data/project_test/.pylintrc
- tests/data/project_test/.vscode/settings.json
- tests/data/project_test/micropy.json
- tests/test_cli.py
- tests/test_project.py
- tests/test_template.py
- tests/test_utils.py
Implements project requirement stubbing. While in a live project, executing:
`micropy add <micropython-module>` *ex: `micropy add blynklib`*
Will:
* add the module to your `micropy.json` file:
```json
{
"name": "Project",
"stubs": { "esp32-pycopy-1.11.0": "1.2.0" },
"packages": {
"blynklib": "*"
},
"dev-packages": {
"micropy-cli": "*"
}
}
```
* retrieve and stub the module, adding it to your `.micropy` folder:
```shell
.micropy
├── esp32-pycopy-1.11.0 -> $HOME.micropy/stubs/esp32-pycopy-1.11.0
├── Project
│   ├── blynklib.py
│   └── blynklib.pyi
└── pycopy -> $HOME/.micropy/stubs/pycopy
```
* and now the module can be used normally, without manually downloading it, adding it to git, etc.
> feat(project): Retrieve and Stub Project Requirements

- micropy/project/project.py
- micropy/stubs/stubs.py
- micropy/utils/helpers.py
- tests/test_utils.py
Allows `micropy-cli` to be executed in a shell without admin privs by falling back on `mklink` when attempting to create a link on windows systems.
As discussed in #44 
Closes #44
> fix(windows): Support User Level Directory Linking

- micropy/project/template.py
- tests/test_template.py
Variable is no longer parsed as of a recent release of ms-python, which is causing the vscode integration to fail.
**BREAKING CHANGE**: No longer compatible with `<=ms-python.python@2019.8.30787` VSCode Extension
Fixes #50
[MS-Python 2019.9.34474 breaks VSCode functionality](https://app.gitkraken.com/glo/board/XQ6dxflUvwAPjp-_/card/XYbODvPbxwAPcRDn)
> fix(hotfix): Remove workspaceRoot var from VSCode Settings

- micropy/project/template.py
- tests/test_template.py
Raises `FileNotFoundError` exception if one attempts to load a micropy project thats missing enabled template files. (Deleted/Ignored via VCS)
> fix: Fails to load Project if Template Files are Missing

- micropy/data/sources.json
- micropy/stubs/source.py
- micropy/utils/helpers.py
- tests/conftest.py
- tests/data/test_repo.json
- tests/data/test_sources.json
- tests/test_stub_source.py
- tests/test_stubs.py
- tests/test_utils.py
Removes the need for an external AWS S3 bucket for hosting stub package archives and uses [micropy-stubs](https://github.com/BradenM/micropy-stubs) directly instead.
This closes BradenM/micropy-stubs#5
> feat: Search/Retrieve Stubs Directly from micropy-stubs

- micropy/cli.py
- micropy/main.py
- micropy/project/project.py
- micropy/project/template.py
- tests/test_cli.py
Allows user to skip template checks by passing a `--skip-checks` flag.
This deals with issues in which the user may not be initiating a project in the environment that it will be developed in.
Also works as temporary solution for #59
> feat: Add Flag for Skipping Template Checks

- micropy/stubs/source.py
StubRepo builds a bad url on Windows machines due to using the pathlib.Path class. Fixed by using a
PurePosixPath instead
> fix: Stub Package Url fails to resolve on Windows

- micropy/project/checks.py
Broken by 06b894f - Windows still works fine
> fix: VSCode Template Check always Fails on Linux

- Pipfile
- micropy/__init__.py
- micropy/cli.py
- micropy/main.py
- micropy/project/__init__.py
- micropy/project/modules/__init__.py
- micropy/project/modules/modules.py
- micropy/project/modules/packages.py
- micropy/project/modules/stubs.py
- micropy/project/modules/templates.py
- micropy/project/project.py
- micropy/project/template.py
- micropy/stubs/stubs.py
- micropy/utils/helpers.py
- setup.py
- tests/conftest.py
- tests/test_cli.py
- tests/test_main.py
- tests/test_project.py
- tests/test_pyboardwrapper.py
Complete restructure of `micropy.project` module. 
Following the composite pattern for re-implementation. This will make it significantly more modular and therefore much easier to extend. Also it doesn't hurt your eyes nearly as much :+1: 
Currently three modules have been split from the old project class: 
* `PackagesModule` - Project Dependencies
* `StubsModule` - Project Level Stub Management
* `TemplatesModule` - Project Templates/Config
The above 3 classes are found under `micropy.project.modules`
The new classes can each be instantiated individually and added to a `Project` container as leafs.
> refactor: Restructure Project Module

- docs/_autosummary/micropy.packages.rst
- docs/modules.rst
- micropy/packages/__init__.py
- micropy/packages/package.py
- micropy/packages/source.py
- micropy/packages/source_package.py
- micropy/packages/source_path.py
- tests/conftest.py
- tests/test_packages.py
- tests/test_project.py
Added `micropy.packages` module which allows different types of dependencies (pypi, local, modules) to all interacted with using the same api. 
This will make implementing #71 and other types of sources (git, url, svn, etc) considerably easier.
> feat(deps): Uniform Dependency API

- micropy/cli.py
- micropy/main.py
- micropy/project/modules/modules.py
- micropy/project/modules/packages.py
- micropy/project/modules/stubs.py
- micropy/project/modules/templates.py
- micropy/project/project.py
- tests/conftest.py
- tests/test_cli.py
- tests/test_main.py
- tests/test_project.py
Removes the restrictions on how/when/where one can add a project module to a project by adding a `PRIORITY` attribute to each module (defaults to lowest). 
The `Project` container will now iterate over its child modules through a queue determined by the child priority, ensuring modules that need to be loaded first are ready.
When adding a project module, do not instantiate it anymore. Just pass the module class plus any args and kwargs. This makes module initialization much easier to deal with.
> feat: Load Project Modules by Priority Queue

- micropy/project/modules/stubs.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/test_highlevel.py
After creating a project, the vscode stub path settings would be deleted upon executing `micropy` a second time. This fix ensures the context for the vscode template is
set and adds a new high level test module to ensure this doesnt happen
again.
This issue is not present on the latest stable release (v3.1.1)
> fix: VSCode Settings failed to populate on reload

- micropy/cli.py
- micropy/exceptions.py
- micropy/packages/source_package.py
- micropy/project/modules/packages.py
- micropy/utils/helpers.py
- tests/conftest.py
- tests/test_cli.py
- tests/test_project.py
- tests/test_utils.py
Fixes:
* `utils.ensure_valid_url` by forcing it to follow `301` or any other redirect status codes. (Fixes #85)
* Adding packages from file path via `PackagesModule.add_from_file` (Fixes #86)
* Attempts to parse path as url (#86)
Changes:
* Added `MicropyException` base exception class
* Added `RequirementException` sub-exception class
* Added `RequirementNotFound` exception
* `utils.get_package_meta` now takes a url rather than a package name
* Any package related exceptions are now handled/reported in the cli module, where it should be. (#86 and #85)
> fix: Handle Package Install Errors

- micropy/utils/helpers.py
- tests/test_utils.py
Changes:
* Ignore any instances of 'rc' in version name when checking for an update (Fixes #91)
> fix(utils): Ignore candidate releases when checking for update

- micropy/config/config.py
Before extending any values in a Config instance, make sure they are of type list to prevent a
TypeError from occuring.
fixes #92
> fix(project): TypeError when adding stubs to existing project

- poetry.lock
- pyproject.toml
Installing micropy right now breaks due to a recent breaking change introduced in a new minor release of markupsafe.
More here: pallets/markupsafe#284
> Pin markupsafe to 2.0.1

- micropy/project/template.py
- micropy/project/template/.vscode/settings.json
- tests/data/project_test/.vscode/settings.json
- Add Pylance support Fix #152
- feat(project): add pylance settings to vscode template.
- feat(project): assume pylance until proper refactorings can be done.
> VSCode Pylance Support

- .gitmodules
- micropy/cli.py
- micropy/main.py
- micropy/utils/stub.py
- poetry.lock
- pyproject.toml
- tests/test_cli.py
- tests/test_main.py
- tests/test_utils.py
- feat(deps): add micropython-stubber as proper library.
- feat(utils): prepare create stubs with codemod variants/modules, update stubmaker imports.
- feat(cli): expose backend option to select pydevice backend.
- feat(main): support create stubs backend parameter, utilize create stub variant.
- test: update existing tests.
> Integrate micropython-stubber as a proper library, utilize create stubs variants.

- micropy/app/stubs.py
- micropy/exceptions.py
- micropy/pyd/abc.py
- micropy/pyd/backend_rshell.py
- micropy/pyd/backend_upydevice.py
- micropy/pyd/consumers.py
- micropy/pyd/pydevice.py
- micropy/utils/stub.py
- tests/app/test_stubs.py
- tests/test_pyd.py
- feat(utils): support compiling createstubs with mpy-cross
- feat(exc): `PyDeviceFileIntegrityError` exception.
- feat(pyd): `NoOpConsumer` implementation.
- fix(pyd): support pushing binary files to pydevice in upydevice backend.
- feat(pyd): file integrity check support in upydevice backend.
- feat(pydevice): file integrity support, simple run in pydevice.
- feat(pyd): implement `remove` across backends.
- feat(app): expose compile, module-defaults flags, integrity in stubs create command.
> Cross Compilation of `createstubs.py` + File Integrity Checks

- micropy/project/template.py
- micropy/project/template/.pylintrc
- micropy/project/template/.vscode/settings.json
- micropy/stubs/stubs.py
- fix(stubs): do not drop firmware name when parsing from dist metadata.
- fix(stubs): always ensure correct pyi stub root paths.
- fix(template): update pylint config to use `MAIN` and `INFERENCE` confidence level.
- fix(template): resolve pylance type-checking / import errors.
Closes #474 
Ref #471
> Resolve pylance/pylint/vscode configuration issues causing import errors and typings issues.

- CHANGELOG.md
- micropy/config/config.py
- micropy/project/template.py
- micropy/pyd/backend_rshell.py
- micropy/utils/helpers.py
- tests/test_config.py
- tests/test_main.py
- tests/test_project.py
- tests/test_stubs.py
Found via `codespell -S poetry.lock -L ure`
> docs: Fix typos
